### PR TITLE
IFI-780 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/IFI-780
This pull is to address: https://github.com/liferay/liferay-npm-tools/issues/136

### CODE REVIEW

**Comment by john-co** [comment]
Hi @wincent, I'm pretty sure this is broken but I'm aiming to append the module name at the end of the classname.

The TEST-frontend-js.xml file should look like this for the management-toolbar js unit test: https://github.com/john-co/liferay-portal/commit/f618e23fc0dace5a91995c01dba47926faac4f2b

**Comment by john-co** [comment]
Hi @wincent, sorry if the code looks hideous but I believe this should work.

**Comment by wincent** [comment]
Thanks @john-co. I'll see if there is any "magic" ✨ to be done and forward this on upstream to https://github.com/liferay/liferay-npm-tools

**Comment by wincent** [comment]
Forwarded here: https://github.com/liferay/liferay-npm-tools/pull/200

Will comment with next steps over on that PR.

**Pull request closed without merging**
